version: '3'
services:
  query_db:
    image: mongo:5.0
    restart: always
    container_name: query_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: myfood_query
    ports:
      - "10002:27017"
  my_food_database:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: oracle
      MYSQL_PASSWORD: oracle
      MYSQL_DATABASE: my_food
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
