version: '3'
services:
  query_db:
    image: mongo:5.0
    restart: always
    container_name: query_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: myfood_query
    ports:
      - "10002:27017"
